# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a44256606b6b6732cf6cdf40677510fbaee98ff0a0c50f103d343f51a3a11127a8de29e7bde37d0b60dec821cca2f4795b8c0dfddf135fb977adc0674935925

test:
  secret_key_base: 8f6e7afb1099059580e2a05f75601e04032953e8a20688ecdc75337e226e3a6ae32b931e60365a3d6d8a8ea71ea08272a77cd6744e89915c12f7e1c8cea0d1bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
